### ISSUE TITLE
`restamp` not working unless `hide-immediately` is set

### ISSUE THREAD

**Issue by paulvarache** [TimvdLippe/iron-lazy-pages#12]
`iron-lazy-pages` do not restamp the selected node when `hide-immediately` is not set to true. Instead it behaves as if `restamp` is was to false and hide/show the already created nodes

You can reproduce this behavior here: https://jsbin.com/zugojesale/1/edit?html,output

**Comment by TimvdLippe** [comment]
Closed in #13
