### ISSUE TITLE
Data binding not working on individual pages

### ISSUE THREAD

**Issue by AndreasGalster** [TimvdLippe/iron-lazy-pages#14]
It seems like data binding with an element within a iron-lazy-page is not working.

`<template is="iron-lazy-page" data-route="">
            <landing-view is-loading={{isLoading}}></landing-view>
          </template>`

This is quite a big issue if you want to fetch data from one component to another. I'm not sure if this is a polymer behavior or something that can be fixed with this component?

**Comment by TimvdLippe** [comment]
Data-binding has been working just fine in my use-cases. Could you create a JSbin that shows the bug?

**Comment by AndreasGalster** [comment]
I'm really sorry, this was my bad. I forgot to set notify:true :/

However, I stumbled over something else related to data-binding.
Following scenario:

```
          <template is="iron-lazy-page" data-route="/messages">
            <messages-view message-id=[[messageId]]></messages-view>
          </template>
          <template is="iron-lazy-page" data-route="/search">
            <search-view message-id={{messageId}}></search-view>
          </template>
```

Within search view i click a button that updates the message-id, then this gets fetched to my messages-view. Works fine if I start on the messages view, go to the search view and from there back to the messages view.

Does not work when I go straight from search-view to messages-view. I'm assuming this is because by the time the search-view updates the message-id via databinding the messages-view hasn't been stamped out yet, so the databinding does not get set. Note, the databinding does work if I update the property after messages-view has been stamped out. 

However, afaik databindings are really just eventlisteners, so since the messages-view gets stamped out after the initial databinding event, the databinding of messages-view will never get set properly. 

Any thoughts how to avoid this?

**Comment by TimvdLippe** [comment]
That is because we are using the native `template` element. It will not stamp out `messages-view` until the route has been matched and consequently not set any data-bindings. If you want a default value in `messageId` the parent mediator should contain this value (e.g. the element that contains the `iron-lazy-pages`).

**Comment by AndreasGalster** [comment]
I've just tried this if I'm understanding you correct.. 

```
Polymer({
  is: 'main-view',
  properties: {
    messageId: {
      type: String,
      value: 'lorem'
    }
  }
});
```

Not sure if I'm doing something wrong but this doesn't work. But if I understand correct, shouldn't this be the same result as the previously mentioned? In both versions the value will be already set in the parent mediator before it gets stamped out.

**Comment by TimvdLippe** [comment]
This should be resolved per our Slack discussion. If you keep on having issues please reopen this issue.
