### ISSUE TITLE
Add notifyResize for paper-tabs

### ISSUE THREAD

**Issue by web-padawan** [TimvdLippe/iron-lazy-pages#15]
When using `paper-tabs`, call of `notifyResize` is required to display selection bar correctly.
This is how it is implemented by `iron-pages`:

```
      _selectedPageChanged: function(selected, old) {
        this.async(this.notifyResize);
      }
```

For now, I have to do this manually when using `iron-lazy-pages`. Would you mind implementing it?

**Comment by TimvdLippe** [comment]
Yes I am open for a pull request. Please include a test case too so I can see how it works in action.

**Comment by TimvdLippe** [comment]
Closing per https://github.com/TimvdLippe/iron-lazy-pages/pull/19#issuecomment-230166622
