### ISSUE TITLE
Demo is broken in Firefox due to 404

### ISSUE THREAD

**Issue by web-padawan** [TimvdLippe/iron-lazy-pages#18]
The demo page uses  `iron-lazy-pages` with some `path` attributes with not existing components:

``` html
    <template is="iron-lazy-page" data-route="bar" path="bla.html">
      Bar page
    </template>
```

When trying to load it, we receive 404:

```
GET http://timvdlippe.github.io/iron-lazy-pages/components/iron-lazy-pages/demo/bla.html?0 404 (Not Found)
```

After that, in Chrome and Safari `loading` is set to `false` (and spinner disappears), and the `Bar page` content is displayed.
However, in Firefox loading occasionally remains on the first click to this tab. 

In the console, the error is shown at this time: 

```
TypeError: Argument 1 of Node.removeChild is not an object.
```

Only after switching tabs several times, `Bar page` is displayed.

**Comment by TimvdLippe** [comment]
Thank you for creating this issue. The error was actually fixed in https://github.com/TimvdLippe/iron-lazy-pages/commit/79c54d38f64a6ca8b6f0b9692efafabcb7072275 but I forgot to update the demo. The demo should now be working again in Firefox :smile:
