### ISSUE TITLE
Import href doesn't work in Firefox

### ISSUE THREAD

**Issue by web-padawan** [TimvdLippe/iron-lazy-pages#2]
The [demo](https://github.com/TimvdLippe/polymer-lazy-application) doesn't work in Firefox. Lazy page content isn't loaded, although routing works as desired.

Only the index file is being loaded, while partials specified in the "path" attribute are not fetched (there are no requests in the Network tab of Firefox devtools).

There are no console errors, the only warning is that "Use of getPreventDefault() is deprecated", but it seems not to be related with the issue.

**upd:** I tried to debug it and something is wrong with the importHref - in Firefox it is never reached, neither onError callback. Firefox version is the newest one

Here is the [workaround](https://gist.github.com/web-padawan/fbf8612258d362cf58ca7f0464bb9567) which works in Firefox kinda like as it is desired.

**upd 2:** the reason is vulcanizing with shards (using gulp-web-component-shards). Without vulcanizing component seems to be OK.

**Comment by TimvdLippe** [comment]
Probably because the demo does not include webcomponents.js. This should be added in the index.html file.

**Comment by TimvdLippe** [comment]
Fixed by https://github.com/TimvdLippe/polymer-lazy-application/commit/438b0e9a606605e48a6a35b85183bd83c1a65c8f
