### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by web-padawan** [TimvdLippe/iron-lazy-pages#22]
I have this error when switching between `iron-lazy-page` instances:

```
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```
- only appears on second load of `iron-lazy-page` children element
- related to Polymer upgrade to 1.6.0

An example as [here](https://sandbox-e0d4b.firebaseapp.com/demo/table/), the file containing `iron-lazy-pages` is [this one](https://github.com/web-padawan/datatable-sandbox/blob/master/src/components/pages/sandbox-demo-page/sandbox-demo-page.html).
(try clicking between tabs multiple times).

The row which causes the issue is follow:

```
document.head.removeChild(e.target || e.srcElement);
```

**Comment by TimvdLippe** [comment]
Opened a pull request to fix this issue in #23, please take a look.
