### ISSUE TITLE
selected-attribute on the stamped page

### ISSUE THREAD

**Issue by aletorrado** [TimvdLippe/iron-lazy-pages#25]
Hi, I need to use the selected-attribute property, which iron-lazy-pages has from Polymer.IronSelectableBehavior, but I've noticed that it's setted on the <template> instead of the stamped page element. It's important for me to know if the page is visible to the user.

How can I do that? Thank you!

**Comment by web-padawan** [comment]
@aletorrado you can listen to `iron-select` event on `iron-lazy-pages` element like this: 

``` js
    _onSelectPage: function (e) {
        console.log(e.detail.item.getAttribute('data-page'));
    }
```

Where `data-page` is your selected-attribute property value.

**Comment by TimvdLippe** [comment]
Please check out #27 which should fix the `selected-attribute` support. Other than that, you can indeed retrieve the currently selected value (in the parent) with the `iron-select` event. If you want to know it in the child element, use #27.
