### ISSUE TITLE
Light DOM children stamped to parent's shadow DOM

### ISSUE THREAD

**Issue by madeleineostoja** [TimvdLippe/iron-lazy-pages#32]
I'm trying to use iron-lazy-pages in a wrapper component to handle pages distributed in its light DOM, like so: 

```
<iron-lazy-pages ...>
  <content select="[is=iron-lazy-page]"></content>
</iron-lazy-pages
```

It works, but active pages are stamped as siblings of `<content>` in the parent's shadow DOM, which defeats the purpose of distributing templates to the light DOM to begin with. 

Noticed support for distributing to light DOM was added in #26, also checked out the new demo from that PR and it stamps to Shadow DOM too. Is that the intended behaviour, or a bug?

**Comment by TimvdLippe** [comment]
I am actually not sure if it is intended or not. But if I understand it correctly: you want the user of the wrapper to also have proper css styling on the iron-lazy-page?

**Comment by madeleineostoja** [comment]
Yep. 

Basically if templates are in the light DOM, then IMO the expected behaviour would be that they get stamped as a sibling (in the light DOM), otherwise you end up with a lot of unintuitive results (page css doesn't get applied, your markup goes 'missing' in the wrapper's shadow root, etc).

**Comment by TimvdLippe** [comment]
Okay yes I agree. Are you willing to investigate and submit a PR? If you are blocked by this, it might take some time by me since I am very busy atm :(

**Comment by madeleineostoja** [comment]
Sure - not familiar at all with how iron-lazy-pages works, but I'll have a poke around.

**Comment by madeleineostoja** [comment]
Looks like an easy fix - rather than passing in the parent [here](https://github.com/TimvdLippe/iron-lazy-pages/blob/master/iron-lazy-pages-behavior.html#L96), set `self.parentNode` [here](https://github.com/TimvdLippe/iron-lazy-pages/blob/master/iron-lazy-page.html#L33) (since `el.parentNode` skips shadow roots).

That means `iron-lazy-page` will stamp to its direct parent (ie: as sibling), rather than stamping as the direct child of `iron-lazy-pages`. Is that a safe assumption? If so I'll submit a PR now.

**Comment by TimvdLippe** [comment]
It should be fixed with changing [this line](https://github.com/TimvdLippe/iron-lazy-pages/blob/master/iron-lazy-page.html#L37) to `self._stamp(self.parentNode)`. That's what you mean right? I think that is correct, please submit your PR :smile:

**Comment by madeleineostoja** [comment]
https://github.com/TimvdLippe/iron-lazy-pages/pull/33 ;-)
