### ISSUE TITLE
Do not require a template definition when lazy loading content

### ISSUE THREAD

**Issue by TimvdLippe** [TimvdLippe/iron-lazy-pages#34]
Currently all pages are required to be an `iron-lazy-page`. This means that they all must be wrapped inside a template. It would be nicer if this requirement is not that strict and instead elements can be loaded without a template, by requiring the attribute `data-path` to be set on the element.

E.g. something like this:

``` html
<iron-lazy-pages attr-for-selected="data-route" selected="{{route}}">
  <template is="iron-lazy-page" data-route="foo" path="foo/foo.html">
    Foo page
  </template>
  <bar-page data-route="bar" data-path="bar/bar.html"></bar-page>
</iron-lazy-pages>
```

**Comment by madeleineostoja** [comment]
This would be awesome. Currently all our 'pages' are just single components, with their imports lazily loaded.

**Comment by TimvdLippe** [comment]
I think we have to introduce this breaking change in 2.0 since custom element extension with `is=` is deprecated in custom elements v1.

**Comment by madeleineostoja** [comment]
worth noting type extension isn't deprecated, just not shipping in WebKit (need to carry a polyfill for safari)

**Comment by sfeederle** [comment]
This would be awesome and improve readability by a lot!

**Comment by JosefJezek** [comment]
@TimvdLippe Any progress?

**Comment by TimvdLippe** [comment]
@JosefJezek Yes you can use `2.0-preview`, the PR is open at https://github.com/TimvdLippe/iron-lazy-pages/pull/44
