### ISSUE TITLE
Make element Polymer 2.0-ready

### ISSUE THREAD

**Issue by GijsWeterings** [TimvdLippe/iron-lazy-pages#36]
Likely a similar process to https://github.com/PolymerElements/iron-pages/compare/2.0-preview

**Comment by web-padawan** [comment]
I think this would require some breaking changes, it's likely that templatizer itself will be refactored. 

In particular, `<template is="iron-lazy-page">` should become just `<iron-lazy-page>`.

**Comment by TimvdLippe** [comment]
I am thinking of getting rid of template all together in #34 If we go down that road, updating to 2.0 should be fairly straightforward I suppose
