### ISSUE TITLE
Will it support neon-animated-pages ? 

### ISSUE THREAD

**Issue by safizn** [TimvdLippe/iron-lazy-pages#4]
Can iron-lazy-pages be used in conjunction with neon-animated-pages ? Is it in the horizon to be added ?
Thanks

**Comment by TimvdLippe** [comment]
I might be able to turn this element into a behavior, with a default defined element. Then it would be usable with the upcoming inheritance. Once that feature is landed, I will try to make it compatible with other *-pages elements.

**Comment by TimvdLippe** [comment]
Currently thinking of creating a completely separate element for it, since the animation logic is quite fundamental in `neon-animated-pages` and making it lazy requires a lot of changes.

**Comment by TimvdLippe** [comment]
With the inspiration of a version of @paulvarache, I have started working on this element. I hope to be able to publish it in a PR soonTM.

**Comment by aletorrado** [comment]
Excellent! Can't wait!

**Comment by TimvdLippe** [comment]
I have pushed a first version of `neon-lazy-pages` in #24. You can try it out yourself with `bower install TimvdLippe/iron-lazy-pages#neon-lazy-pages`. Please provide feedback on the usage and any bugs you encounter on the pull request.

**Comment by TimvdLippe** [comment]
It's probably better to create a separate repository for the neon-lazy-pages and instead refactor iron-lazy-pages in such a way that neon-lazy-pages can inherit almost all code of it. For now I am still waiting for feedback on #24
