### ISSUE TITLE
restamp="false" will fail

### ISSUE THREAD

**Issue by sebastianroming** [TimvdLippe/iron-lazy-pages#46]
If you set `restamp="false"`, the element will be removed and injected from DOM after loading the correct page.
As the default value is `false`, you can get rid of the attribute, but if you include it, the output doesn't work as expected.

**Comment by TimvdLippe** [comment]
This is the correct behavior of boolean attributes in HTML. For more information see http://stackoverflow.com/a/4139805/2761676
