### ISSUE TITLE
Add functionality to run entry and exit animation at the same time

### ISSUE THREAD

**Issue by roelvanhoof** [TimvdLippe/iron-lazy-pages#47]
Add functionality to run entry and exit animation at the same time

It seems neon-animated-pages does this also, looks a lot nicer.

**Comment by TimvdLippe** [comment]
It seems that this is more complicated than I had expected, as hiding of the page is performed after the animation is finished. I am quite busy the next week, so if you are able to work on a PR that would be very nice! Else I will continue working on it in about 2 weeks.

**Comment by TimvdLippe** [comment]
I have decided to remove `neon-lazy-pages` for the time being. It was too maintenance heavy and had several animation issues.
