### ISSUE TITLE
Fix Firefox Travis build

### ISSUE THREAD

**Issue by TimvdLippe** [TimvdLippe/iron-lazy-pages#49]
The Travis build keeps on failing on Firefox, but it is working just fine locally. Somehow this needs to be fixed by correctly configuring Travis.

**Comment by jpradelle** [comment]
I think this one https://github.com/TimvdLippe/iron-lazy-pages/pull/50 should solve the issue.
It was not working for me.

**Comment by TimvdLippe** [comment]
Fixed in #50, thanks a lot @jpradelle !
