### ISSUE TITLE
neon-lazy-pages exit/entry animation not contiguous

### ISSUE THREAD

**Issue by srijken** [TimvdLippe/iron-lazy-pages#53]
The exit animation of the old page runs, then after a while the entry of the new page runs. 
When using neon-animated-pages they are continguous, which makes it feel much faster.

**Comment by TimvdLippe** [comment]
Happy to accept PRs to improve this behavior. I don't personally use neon-lazy-pages and am really bad at animations and such :P

**Comment by TimvdLippe** [comment]
I have decided to remove `neon-lazy-pages` for the time being. It was too maintenance heavy and had several animation issues.
