### ISSUE TITLE
data-path is relative to location of embedding element

### ISSUE THREAD

**Issue by ronnyroeller** [TimvdLippe/iron-lazy-pages#57]
We use `iron-lazy-pages` within a `app-drawer-layout`:

```
<app-drawer-layout>
  <app-drawer slot="drawer">...</app-drawer>

  <iron-lazy-pages attr-for-selected="name" selected="[[_selected]]" load-async>
    <my-home name="home" data-path="home.html"></my-home>
 ...
```

Loading the application in Chrome (Fedora) leads to an error because file `http://localhost:8081/bower_components/app-layout/app-drawer-layout/home.html` can't be found.

It works when changing the relative path to
```
  <my-home name="home" data-path="../../../elements/home.html"></my-home>
```

I would expect that the path in `data-path` is relative to the base path of the application (same as `<link rel="import" href="home.html">`.

**Comment by TimvdLippe** [comment]
Hm yes that is what I feared :cry: My intention was to resolve to the location that the host node is located. E.g. if you have your `my-app` outside of your `src/`, then you don't need to duplicate that `src/` on all of your routes. My fear was that it was probably too optimistic, which you point out. Probably the best thing is to just revert this, WDYT?

**Comment by ronnyroeller** [comment]
Clever idea indeed.
Yet, as a user I'd expect the `data-path` to behave like `<link rel="import" href="...">` because they seem to do something very similar (in a different context).

**Comment by TimvdLippe** [comment]
Yes and `rel="import"` resolves relative to the current document. That would mean that `src/` should not be necessary to be appended to every route. In other words: in 1.0 you needed to have the full absolute path, in 2.0 I tried to fix that by being more "clever" and try to resolve relative to the location of the element. However, it appears that the `host` is actually not set in your element, as it would have resolved using that element instead. I will need to debug more thoroughly, please give me a couple of mins :smile:

**Comment by TimvdLippe** [comment]
Internet was down, but I managed to push now :joy: @ronnyroeller could you try out #58 (`bower install TimvdLippe/iron-lazy-pages#fix-resolving`) and check if the issue has been resolved?

**Comment by ronnyroeller** [comment]
Awesome! The fix works for me.
