### ISSUE TITLE
Kill the component once no longer selected

### ISSUE THREAD

**Issue by AndreasGalster** [TimvdLippe/iron-lazy-pages#59]
Is it possible to kill a component once it is no longer needed/selected? E. g., we have one page with podcasts, there I can play a podcast. Now if I switch route, the podcast will still play since the component/podcast player is still in the DOM.

**Comment by TimvdLippe** [comment]
Yes that usecase should be fixed in #56 with dom-if support. Could you try it out locally?

**Comment by TimvdLippe** [comment]
@AndreasGalster Have you had some time to test out #56? I would like to merge it once I know it works for your usecase :smile: 

You can install it via `bower install TimvdLippe/iron-lazy-pages#dom-if`

**Comment by AndreasGalster** [comment]
Hey, I tried it out but couldn't get it to work (yet). I will experiment a bit more now, will let you know in a while :)... oooh I didn't know it's in a separate branch, installing ;)!

**Comment by AndreasGalster** [comment]
I don't think it is working. This should work, no?
```
<iron-lazy-pages attr-for-selected='route' selected=[[path]]>
	<podcasts-view route='/podcasts' logged-in=[[loggedIn]] path-reload=[[path]] ink-box></podcasts-view>
	<template is='dom-if' route='/podcast' restamp>
	    <podcast-detail-view logged-in=[[loggedIn]] podcast-id=[[queryParams.id]] ink-box></podcast-detail-view>
	</template>
	<podcast-detail-view route='/podcast' logged-in=[[loggedIn]] podcast-id=[[queryParams.id]] ink-box></podcast-detail-view>
</iron-lazy-pages>
```

Without the dom-if route='/podcast' works, like this:

```
<podcast-detail-view route='/podcast' logged-in=[[loggedIn]] podcast-id=[[queryParams.id]] ink-box></podcast-detail-view>
```

Does this actually work, or does the route parameter in this case expect a true/false? According to your demo in your commit this should work.

**Comment by TimvdLippe** [comment]
Which version of Polymer are you using? Can you change it to `<dom-if>` and
see if it works?

**Comment by ernsheong** [comment]
https://github.com/TimvdLippe/iron-lazy-pages/pull/56 is working fine for me. Thanks @TimvdLippe !!

**Comment by TimvdLippe** [comment]
Closing as #56 has been merged.
