### ISSUE TITLE
iron-lazy-pages for polymer 3

### ISSUE THREAD

**Issue by robertosobachi** [TimvdLippe/iron-lazy-pages#63]
Hi, I've created a new version of your iron-lazy-pages for polymer 3.0 that works with `<dom-if>` to mainly have css stylesheets lazy-loaded. [Should <link> work inside Shadow DOM?](https://github.com/w3c/webcomponents/issues/628)

```
  static get template() {
    return `
      <link rel="stylesheet" href="./my-view1/my-view1.css">
   ...
```

I still need to run some test but you can have a look at it here: [https://github.com/robertosobachi/iron-lazy-pages/tree/3.0-preview](https://github.com/robertosobachi/iron-lazy-pages/tree/3.0-preview)

I can create a pull request if you're happy with it later on when I'm sure all tests are covered.

I've also created a new version of the polymer-starter-kit that runs polymer 3-preview with gulp and your iron-lazy-pages here [https://github.com/robertosobachi/polymer-starter-kit](https://github.com/robertosobachi/polymer-starter-kit)

**Comment by TimvdLippe** [comment]
Hey Roberto,

Thanks for doing the initial investigation! Inspecting the diff, I see you made some other breaking changes as well. I don't want to make any other breaking changes in 3.0-preview other than the loading mechanism.

Moreover, your version does not do lazy-loading (with dynamic `import`), but only supports `<dom-if>`. I think we have to wait till browsers ship dynamic `import` before trying to figure out how 3.0-preview looks like. (We should have plenty of time still, as Polymer 3 will also wait for that).

Other than that, thanks for the effort! Once these last issues are addressed, we can review and merge 👍

**Comment by robertosobachi** [comment]
Thanks Tim! Yes, agree, if Polymer 3 will wait for dynamic `import` it's fine to wait until we can get a proper lazy-loading.

Thanks!

I think you can close this issue.

**Comment by TimvdLippe** [comment]
I prefer to keep it open so we can point people to this discussion and
understand the reasoning :) And Polymer 3 is still a task I have to do for
the future, so the issue is still valid.

**Comment by robertosobachi** [comment]
FYI, I'm now using `import()` and tested on Chrome 64.0 Canary. I know there's a long way before `import()` will be widely supported but I'm happy to play with useful Polymer components on my spare time ;)

**Comment by TimvdLippe** [comment]
For everyone looking for the 3.0-preview version of this element: it is blocked on https://tc39.github.io/proposal-dynamic-import/ being accepted and implemented by major browsers. Once the spec is accepted, a polyfill can be created to start testing this element.

You are advised **NOT** to use Polymer 3.0-preview yet until dynamic `import` is ready. Else your application can not be PRPL, which negates the need for this element.

**Comment by TimvdLippe** [comment]
A modulizered version of this element is available at https://github.com/TimvdLippe/iron-lazy-pages/tree/3.0-preview Note that the actual loading still uses HTML imports, so I think the branch is still useless in its current form (until dynamic import lands) :joy:

**Comment by AndreasGalster** [comment]
Will this be published on NPM soon? I understand it's not ready yet due to HTML imports, though maybe an @next publish would do the trick? However, for people like me who are not making use of the importHref funtionality, this element works perfectly fine already with the 3.0 version.

**Comment by TimvdLippe** [comment]
Hm it seems that my modulizer output of `iron-lazy-pages` is far from working (demo's do not work and tests do not run), so I am not comfortable with publishing to npm yet. Mostly because atm I have no extra time to maintain and update the npm version :cry: Once modulizer is up-to-date and more stable, I can publish a working version.

**Comment by TimvdLippe** [comment]
Version is up at #68. Please let me know if it is actually working as intended. Note that I had to push to a new branch (`3.0-preview-2`) to not potentially break current installations relying on the Bower branch `3.0-preview`.

**Comment by 200Puls** [comment]
Hi @TimvdLippe thanks for the update.
It seems to work in my application. I can not fully test yet as there are some things still missing migration but thus far its looking good.

**Comment by TimvdLippe** [comment]
Iron-lazy-pages is now on NPM: https://www.npmjs.com/package/iron-lazy-pages
