### ISSUE TITLE
lazy loading algo based on template

### ISSUE THREAD

**Issue by frank-dspeed** [TimvdLippe/iron-lazy-pages#64]
---

**Comment by TimvdLippe** [comment]
Hello @frank-dspeed !

I am a bit confused by this issue. As far as I know, the Polymer team has not planned Polymer 4 yet. As such, I am not sure how we can advance forward. Moreover, the `<template>` syntax in the v1 of this element was an anti-pattern imo. It made performance a lot harder, as you essentially hid the implementation. You simply could not lazy-load. The current implementation allows a lot more examples, but also `<template is="dom-if">` if the developer wants to trash the DOM elements when switching routes.

As the current implementation is very flexible and I am not sure what Polymer 4 will include, I am going to close this issue. If there is any actionable item right now that you would like to propose, feel free to reopen this issue!

Thanks,
Tim
