### ISSUE TITLE
connectedCallback call order

### ISSUE THREAD

**Issue by toliklunev** [TimvdLippe/iron-lazy-pages#65]
I'm have a problem with connectedCallback ordering. Normal usage of webcomponents calls connectedCallback's from child to parent. If I write a console.log at connectedCallback's, I got:
Child
Parent

But when I'm using iron-lazy-pages, I got:
Parent
Child

I prepared  a example, that demonstrate the issue: https://codepen.io/codefucker/project/editor/AVLJpr

**Comment by TimvdLippe** [comment]
This is actually native behavior. An example with the same output not using `iron-lazy-pages`: http://jsbin.com/jegegaraza/edit?html,console,output

If you would like to keep the order, I advise you to not use the `template` but instead just keep the DOM node in there.
