### ISSUE TITLE
MIME Exception 

### ISSUE THREAD

**Issue by Exnadella** [TimvdLippe/iron-lazy-pages#72]
Hi,

We've converted our polymer 1.x app to 3.x manually. We've executed the 1.x project through java app, following the same procedure in the 3.x project we are getting MIME exception i.e, we are unable to import polymer elements from this statement.
import {PolymerElement, html} from '@polymer/polymer/polymer-element.js';

The pages execute fine independently using Polymer serve.

How to resolve the issue.

The polymer components are not loading.
Do we need to change the path while loading.  How to do it ?
Do we need to change ES6 to AMD modules 

Ranganath.

**Comment by Exnadella** [comment]
We've converted our polymer 1.x project to 3.x manually. We've executed the 1.x project through java app,  following the same in the 3.x project we are getting MIME exception i.e, we are unable to import polymer elements from this statement.
import {PolymerElement, html} from '@polymer/polymer/polymer-element.js';

**Comment by Exnadella** [comment]
We've converted our polymer 1.x app to 3.x manually. We've executed the 1.x project through java app,  following the same procedure in the 3.x project we are getting MIME exception i.e, we are unable to import polymer elements from this statement.
import {PolymerElement, html} from '@polymer/polymer/polymer-element.js';  

The pages execute fine independently using Polymer serve.

**Comment by TimvdLippe** [comment]
@Exnadella I think you are running into the breaking change I made in 2.0: https://github.com/TimvdLippe/iron-lazy-pages/releases/tag/v2.0.0 See the point `Paths are resolved relative to the parent of iron-lazy-pages`

**Comment by Exnadella** [comment]
We were able to resolve the issue by providing the relevant paths in Polymer.Json file
