### ISSUE TITLE
Elements not loading in Firefox

### ISSUE THREAD

**Issue by vimalraj-a** [TimvdLippe/iron-lazy-pages#9]
In Mozilla failed to remove an element after loading the element definitions. Seams
`e.srcElement` is empty.

Getting error at this line : https://github.com/TimvdLippe/iron-lazy-pages/blob/master/iron-lazy-pages.html#L300

**Comment by TimvdLippe** [comment]
Switched to `e.target` instead. Thanks for reporting!
